# coding: utf-8

# flake8: noqa

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.avisos_cap_api import AvisosCapApi
from swagger_client.api.indices_incendios_api import IndicesIncendiosApi
from swagger_client.api.informacion_satelite_api import InformacionSateliteApi
from swagger_client.api.maestro_api import MaestroApi
from swagger_client.api.mapas_y_graficos_api import MapasYGraficosApi
from swagger_client.api.observacion_convencional_api import ObservacionConvencionalApi
from swagger_client.api.prediccion_maritima_api import PrediccionMaritimaApi
from swagger_client.api.predicciones_especificas_api import PrediccionesEspecificasApi
from swagger_client.api.predicciones_normalizadas_texto_api import PrediccionesNormalizadasTextoApi
from swagger_client.api.productos_climatologicos_api import ProductosClimatologicosApi
from swagger_client.api.red_radares_api import RedRadaresApi
from swagger_client.api.red_rayos_api import RedRayosApi
from swagger_client.api.redes_especiales_api import RedesEspecialesApi
from swagger_client.api.valores_climatologicos_api import ValoresClimatologicosApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.model200 import Model200
from swagger_client.models.model401 import Model401
from swagger_client.models.model404 import Model404
from swagger_client.models.model429 import Model429
